### ISSUE TITLE
Проект заброшен?

### ISSUE THREAD

**Issue by gluhow** [evgeniye777/Songarchive#3]
За последний месяц нет ни одного коммита

**Comment by evgeniye777** [comment]
Почему, я же потом второй выложил
Он называется MyproektTwo
Он не виден?



Отправлено из мобильной Почты Mail.ru


вторник, 15 октября 2019 г., 12:15 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by gluhow** [comment]
Последний коммит 29 дней назад https://github.com/evgeniye777/Songarchive/commit/dd527e41373db521ce8a5517fcd75936bc6ec049
